- name: generate admin csr
  copy:
    dest: "{{ role_path }}/files/admin-csr.json"
    content: "{{ admin_csr | to_json }}"

- name: generate admin cert
  shell: cfssl gencert -ca=../../ca.pem -ca-key=../../ca-key.pem -config={{ role_path }}/files/ca-config.json -profile=kubernetes {{ role_path }}/files/admin-csr.json | cfssljson -bare admin