- name: generate admin_cert
  copy:
    dest: "{{ role_path }}/files/admin-csr.json"
    content: "{{ admin_csr | to_json }}"

- name: generate admin cert
  shell: cfssl gencert -ca={{ role_path }}/ca.pem -ca-key={{ role_path }}/ca-key.pem -config={{ role_path }}/files/ca-config.json -profile=kubernetes {{ role_path }}/files/admin-csr.json | cfssljson -bare admin