- name: generate kube proxy csr
  copy:
    dest: "{{ role_path }}/files/kube-proxy-csr.json"
    content: "{{ kube_proxy | to_json }}"

- name: generate kube proxy cert
  shell:  cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config={{ role_path }}/files/ca-config.json -profile=kubernetes {{ role_path }}/files/kube-proxy-csr.json | cfssljson -bare {{ role_path }}/files/kube-proxy