- name: generate kube controller manager csr
  copy:
    dest: "{{ role_path }}/files/kube-controller-manager-csr.json"
    content: "{{ kube_controller_manager | to_json }}"

- name: generate kube controller manager certificate
  shell: cfssl gencert -ca={{ role_path }}/files/ca.pem -ca-key={{ role_path }}/files/ca-key.pem -config={{ role_path }}/files/ca-config.json -profile=kubernetes {{ role_path }}/files/kube-controller-manager-csr.json | cfssljson -bare {{ role_path }}/files/kube-controller-manager