- name: service account csr
  copy:
    dest: "{{ role_path }}/files/service-account-csr.json"
    content: "{{ service_account | to_json }}"

- name: generate service account certificate
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config={{ role_path }}/files/ca-config.json -profile=kubernetes {{ role_path }}/files/service-account-csr.json | cfssljson -bare service-account